- hosts: all
  tasks:
    - file: path=/etc/zabbix/zabbix_agentd.d/ state=directory owner=root group=root mode=0755
      become: True
    - copy: src=custom.conf dest=/etc/zabbix/zabbix_agentd.d/
      become: True

    - name: download .deb for Debian 9 (Stretch)
      get_url:
        url="http://repo.zabbix.com/zabbix/3.4/debian/pool/main/z/zabbix-release/zabbix-release_3.4-1+stretch_all.deb"
        dest=/tmp/zabbix.deb
      when: ansible_distribution == "Debian" and ansible_distribution_major_version|int == 9
    - name: download .deb for Ubuntu 16 (Xenial)
      get_url:
        url="http://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1+xenial_all.deb"
        dest=/tmp/zabbix.deb
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 16
    - name: download .deb for Ubuntu 14 (Trusty)
      get_url:
        url="http://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1+trusty_all.deb"
        dest=/tmp/zabbix.deb
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 14
    - apt: deb=/tmp/zabbix.deb
      become: True
    - apt: name=zabbix-agent update_cache=yes
      become: True

