- hosts: all
  gather_subset: "!ohai"
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
  tasks:
    - debug: msg="distr={{ ansible_distribution }} version={{ ansible_distribution_major_version }} codename={{ ansible_facts.lsb.codename }} release={{ ansible_distribution_release }}"

    - name: download .deb for Debian
      get_url:
        url="http://repo.zabbix.com/zabbix/4.4/debian/pool/main/z/zabbix-release/zabbix-release_4.4-1+{{ ansible_facts.lsb.codename }}_all.deb"
        dest=/tmp/zabbix.deb
      when: ansible_distribution == "Debian" and ansible_facts.lsb.codename != "bullseye"
    - name: download .deb for Ubuntu
      get_url:
        url="http://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.4-1+{{ ansible_facts.lsb.codename }}_all.deb"
        dest=/tmp/zabbix.deb
      when: ansible_distribution == "Ubuntu"
    - apt: deb=/tmp/zabbix.deb
      become: True
      when: (ansible_distribution == "Debian" and ansible_facts.lsb.codename != "bullseye") or ansible_distribution == "Ubuntu"
    - apt: name=zabbix-agent update_cache=yes cache_valid_time=2419200
      become: True

    - copy: src=custom.conf dest=/etc/zabbix/zabbix_agentd.d/
      become: True
    - lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Hostname=' line='#Hostname=Zabbix server'
      become: True
    - lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Server=' line='Server=127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
      become: True

