- hosts: all
  gather_subset:
    - "!ohai"
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
  tasks:
    - debug: msg="distr={{ ansible_distribution }} version={{ ansible_distribution_major_version }} codename={{ ansible_facts.lsb.codename }} release={{ ansible_distribution_release }}"

    - apt: deb="http://repo.zabbix.com/zabbix/5.0/debian/pool/main/z/zabbix-release/zabbix-release_5.0-1+{{ ansible_facts.lsb.codename }}_all.deb"
      become: True
      when: ansible_distribution == "Debian" and ansible_facts.lsb.codename != "bullseye"
    - apt: deb="http://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+{{ ansible_facts.lsb.codename }}_all.deb"
      become: True
      when: ansible_distribution == "Ubuntu"
    - apt: name=zabbix-agent update_cache=yes state=latest
      become: True

    - copy: src=custom.conf dest=/etc/zabbix/zabbix_agentd.d/
      become: True
    - lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Hostname=' line='#Hostname=Zabbix server'
      become: True
    - lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Server=' line='Server=127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
      become: True

    - systemd:
        name: zabbix-agent.service
        enabled: yes
        state: started
        daemon_reload: yes
      become: True

